### ISSUE TITLE
Issue-bump dependencies to latest

### ISSUE THREAD

**Issue by doraemon-35** [doraemon-35/musl#12]
Automated Review Comments
Issues in Dockerfile:
  - (1, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')

**Comment by drone-1x** [comment]
I got it.
