### ISSUE TITLE
Issue-back to nightly cron

### ISSUE THREAD

**Issue by doraemon-35** [doraemon-35/musl#2]
Automated Review Comments
Issues in .travis.yml:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
  - (33, 'Line exceeds 80 characters')
Issues in Dockerfile:
  - (7, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (34, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')
  - (59, 'Line exceeds 80 characters')
  - (64, 'Line exceeds 80 characters')
  - (65, 'Line exceeds 80 characters')
  - (71, 'Line exceeds 80 characters')
  - (77, 'TODO found')
  - (78, 'Line exceeds 80 characters')
  - (80, 'Line exceeds 80 characters')
  - (86, 'Line exceeds 80 characters')
  - (89, 'Line exceeds 80 characters')
  - (90, 'Line exceeds 80 characters')
  - (91, 'Line exceeds 80 characters')
  - (96, 'Line exceeds 80 characters')
  - (98, 'Line exceeds 80 characters')
  - (102, 'Line exceeds 80 characters')
  - (105, 'Line exceeds 80 characters')
  - (106, 'Line exceeds 80 characters')
  - (108, 'Line exceeds 80 characters')
  - (110, 'Line exceeds 80 characters')
  - (117, 'Line exceeds 80 characters')
  - (118, 'Line exceeds 80 characters')
  - (120, 'Line exceeds 80 characters')
Issues in LICENSE:
  - (8, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
Issues in Makefile:
  - (18, 'Hardcoded string found')
  - (43, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
Issues in README.md:
  - (5, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
  - (52, 'Line exceeds 80 characters')
  - (63, 'Line exceeds 80 characters')
  - (72, 'Line exceeds 80 characters')
  - (75, 'Line exceeds 80 characters')
  - (82, 'Line exceeds 80 characters')
  - (85, 'Line exceeds 80 characters')
  - (87, 'Line exceeds 80 characters')
  - (90, 'Line exceeds 80 characters')
  - (92, 'Line exceeds 80 characters')
  - (113, 'Line exceeds 80 characters')
  - (116, 'Line exceeds 80 characters')
  - (126, 'Line exceeds 80 characters')
  - (129, 'Line exceeds 80 characters')
  - (132, 'Line exceeds 80 characters')
Issues in test.sh:
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (45, 'Line exceeds 80 characters')
  - (45, 'Hardcoded string found')
Issues in test/curlcrate/Cargo.toml:
  - (4, 'Hardcoded string found')
Issues in test/curlcrate/src/main.rs:
  - (9, 'Line exceeds 80 characters')
Issues in test/dieselpgcrate/Cargo.toml:
  - (4, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
Issues in test/dieselpgcrate/src/main.rs:
  - (28, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
  - (41, 'Line exceeds 80 characters')
Issues in test/dieselsqlitecrate/Cargo.toml:
  - (4, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
Issues in test/dieselsqlitecrate/src/main.rs:
  - (28, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
  - (41, 'Line exceeds 80 characters')
Issues in test/hypercrate/Cargo.toml:
  - (4, 'Hardcoded string found')
Issues in test/hypercrate/src/main.rs:
  - (22, 'Line exceeds 80 characters')
Issues in test/pkgconf/Cargo.toml:
  - (4, 'Hardcoded string found')
Issues in test/pkgconf/src/main.rs:
  - (8, 'Hardcoded string found')
Issues in test/plaincrate/Cargo.toml:
  - (4, 'Hardcoded string found')
Issues in test/pqcrate/Cargo.toml:
  - (4, 'Hardcoded string found')
Issues in test/pqcrate/src/main.rs:
  - (3, 'Line exceeds 80 characters')
Issues in test/rocketcrate/Cargo.toml:
  - (4, 'Hardcoded string found')
Issues in test/serdecrate/Cargo.toml:
  - (4, 'Hardcoded string found')
Issues in test/serdecrate/src/main.rs:
  - (20, 'Hardcoded string found')
Issues in test/sslcrate/Cargo.toml:
  - (4, 'Hardcoded string found')
Issues in test/zlibcrate/Cargo.toml:
  - (4, 'Hardcoded string found')
Issues in test/zlibcrate/src/main.rs:
  - (51, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (58, 'Line exceeds 80 characters')
  - (58, 'Hardcoded string found')
  - (63, 'Hardcoded string found')

**Comment by angel-1x** [comment]
I got it.
