### ISSUE TITLE
Issue-diesel works without forks, but only up to 1.2 on nightly

remove reliance on forks and pin version to 1.2 until
https://github.com/diesel-rs/diesel/issues/1700 gets resolved either in
rust or diesel.

### ISSUE THREAD

**Issue by doraemon-35** [doraemon-35/musl#32]
Automated Review Comments
Issues in README.md:
  - (2, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
Issues in test/dieselpgcrate/Cargo.toml:
  - (2, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
Issues in test/dieselpgcrate/src/main.rs:
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
Issues in test/dieselsqlitecrate/Cargo.toml:
  - (2, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
Issues in test/pqcrate/Cargo.toml:
  - (1, 'Hardcoded string found')

**Comment by angel-1x** [comment]
I got it.
