### ISSUE TITLE
Issue-release the new stable first

### ISSUE THREAD

**Issue by doraemon-35** [doraemon-35/musl#34]
Automated Review Comments
Issues in .travis.yml:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')

**Comment by drone-1x** [comment]
I got it.
