### ISSUE TITLE
Issue-back to nightly cron

### ISSUE THREAD

**Issue by doraemon-35** [doraemon-35/musl#8]
Automated Review Comments
Issues in .travis.yml:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')

**Comment by angel-1x** [comment]
I got it.
